name: Metrics
on:
  # Schedule updates (every 3 hours)
  schedule: [{cron: "0 */3 * * *"}]
  # Allow manual trigger on demand
  workflow_dispatch:
  # Run workflow when pushing to master or main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: master
          filename: github-metrics.svg
          # Misc  
          config_timezone: Asia/Dhaka
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base: "header, community, metadata"
          plugin_stars: yes
          plugin_stars_limit: 5
