name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Misc  
          config_timezone: Asia/Dhaka
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base: "header, community, metadata"
          plugin_stars: yes
          plugin_stars_limit: 5
